/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.SparkWeave;

import org.junit.Before;
import org.junit.Test;
import java.util.List;

public class SparkWeaveConnectorDriver
{
    @Override
    protected String getConfigResources()
    {
        return "mule-config.xml";
    }

    @Test
    public void shouldObtaintAMetada() throws Exception
    {

        SparkWeaveConnector connector = new SparkWeaveConnector();
        connector.setServer("mblock-vm1");
        connector.setUserEmail("mblock@sparkweave.com");
        connector.setPassword("123abc");

        List<String> list = connector.list("/My folder");
        System.out.println(Arrays.toString(list.toArray()));
    }
}
