/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.SparkWeave;

import org.mule.api.MuleEvent;
import org.mule.construct.Flow;
import org.mule.tck.FunctionalTestCase;
import org.mule.tck.AbstractMuleTestCase;

import org.junit.Test;

public class SparkWeaveConnectorTest extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return "mule-config.xml";
    }

    @Test
    public void shouldObtaintAMetada() throws Exception
    {

        // SparkWeaveConnector connector = new SparkWeaveConnector();
        // connector.setServer()
        // connector.setAccessToken(ACCESS_KEY);
        // connector.setAccessTokenSecret(ACCESS_SECRET);
        // connector.setAppKey(APP_KEY);
        // connector.setAppSecret(APP_SECRET);
        // connector.setServer("api.dropbox.com");
        // connector.setDebug(true);

        // List<String> list = connector.list("/My folder");
        // System.out.println(Arrays.toString(list.toArray()));;
    }
}
